# Generated by Django 5.1.7 on 2025-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
    ]
