# Generated by Django 5.1.7 on 2025-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_demandepriseencharge_messagepatientkine_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diplôme'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='diplome_file',
            field=models.ImageField(blank=True, null=True, upload_to='diplomes/', verbose_name='Photo du diplôme'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wilaya',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wilaya'),
        ),
    ]
