# Generated by Django 5.1.7 on 2025-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Produits de soins et de massage', 'Produits de soins et de massage'), ('Matériel de rééducation fonctionnelle', 'Matériel de rééducation fonctionnelle'), ('Équipements de renforcement musculaire', 'Équipements de renforcement musculaire'), ('Produits de cryothérapie', 'Produits de cryothérapie'), ('Appareils électromédicaux', 'Appareils électromédicaux'), ('Supports et orthèses', 'Supports et orthèses'), ('Mobilier et accessoires professionnels', 'Mobilier et accessoires professionnels'), ('autre', 'Autre')], default='autre', max_length=60),
        ),
    ]
